# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 581a530de2b7547575cc1f12ec274486060c0537a1cd52b7f371fc7862e1da9ea673a9d9ac61485862339fad5b92129fa7420f49ebb8d9a381d58c7a90fb96c8

test:
  secret_key_base: 71f4e321c407ee7d5a3c595583458f0a19b5a589b6b72ac1858aa83ef2fcf468802cef94583b6e3f278e50161c6da9aa255160800b2848be94469ce201df8f4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
